### ISSUE TITLE
Ask for pose_deepercut.py

### ISSUE THREAD

**Issue by Limbbo** [classner/generating_people#10]
Hello :)
Could you provide your code, which should be located in

**~/up/pose/pose_deepercut.py**

I can't find this code. Thanks.

**Comment by classner** [comment]
Hi @Limbbo ,

that's the human pose estimation code from the "unite the people" repository, which you can find here: https://github.com/classner/up . You can configure the paths to be different in `config.py`, in this case with the `UP_FP`.

Best,
Christoph
