### ISSUE TITLE
error when run 05_run_fits.sh

### ISSUE THREAD

**Issue by Limbbo** [classner/generating_people#11]
Thank you for answering my question last time and I have another question.

To set up the data, i run the scripts iteratively .
But when run 05_run_fits.sh, i got this error.
**IndexError: index 4 is out of bounds for axis 1 with size 3**

Also, you told me that **'pose_deepercut.py'** code is in 'https://github.com/classner/up'
but there is no  'pose_deepercut.py'  and only other code, so i run the 'pose.py'.

Thanks.

**Comment by classner** [comment]
So the pose script you use is alright. Hmmm, can you give a bit more context for this error message?

**Comment by Limbbo** [comment]
I think I have an error while running 526 line in **'up/3dfit/bodyfit.py'** code.
And I checked the **sv.pose** through the log. Is the column 4 correct?

Attach the error logs together at the bottom. 

![image](https://user-images.githubusercontent.com/37970556/54253583-123ce300-4593-11e9-82c9-ab405920590d.png)

Thank you for your answer.

**Comment by classner** [comment]
I don't really know what's going on here. I assume you changed the code or tried to prepare new data for it that may not match our old format entirely. I understand that this error is raised by chumpy (the optimizer). I would make sure that the shape of the objectives matches and debug from there.
