### ISSUE TITLE
Conditioning on colour

### ISSUE THREAD

**Issue by kazimpal87** [classner/generating_people#12]
Hi, are there any documentation about how to use the generate_conditioned script? Specifically I'd like to specify clothing colour as described in the paper. Thanks

**Comment by classner** [comment]
Hi @kazimpal87 ! Thanks for your interest in the project! The `generate_conditioned` script is for the conditional sketch module, generating body part segments conditioned on a body pose. The model that does color conditioning is not part of this repository. It is, however, fairly similar to the existing portray module (see the experiment `PM`) with an additional input image that has a color for every body segment. I trained this in a supervised way by just using the median colors for the segments. Let me know if you have any more questions.
