### ISSUE TITLE
Hello! I run your code successfully based on py3.7, tf2.2. How can I generate different clothes on one person?

### ISSUE THREAD

**Issue by zzk2021** [classner/generating_people#14]
![image](https://user-images.githubusercontent.com/73774678/214259703-a87b300d-96e0-4e79-9699-d7ca70974a6b.png)

This is the result. But this is not what I want.
I hope that we could generate different clothes on one person, not one person mapping to one cloth.
Could you provide some options? Thanks!

**Comment by classner** [comment]
Hi @zzk2021 !

Thanks for reaching out! Unfortunately, this project does not disentangle person identity and clothing style as is and can’t be used for person specific generation. There are followup works attempting this and unless you want to significantly modify and develop this code base I have to refer you to those.
