### ISSUE TITLE
The code of "pose deeper cut" 

### ISSUE THREAD

**Issue by sergeywong** [classner/generating_people#2]
When I run the code "generation/tools/04_run_deepercut.sh", I find that I have no the module "~/git/up" stated in the "config.py" at Line 13. How can I get the exact code?

I find the project DeepCut(http://pose.mpi-inf.mpg.de/#code) as described in the paper. But it doesn't provide the code used in this project.

**Comment by sergeywong** [comment]
I find it in https://github.com/classner/up. Maybe it's better to add this to the requirement in readme file.

**Comment by classner** [comment]
Hi Surge!

I'm glad you found it and I included it in the README file like suggested. Sorry for the hassle.

Best,
Christoph

**Comment by haithanhp** [comment]
Hi @classner & @sergeywong,
Did you successfully run ./05_run_fits.sh for create 3D model? When I tried to run and got a crash when creating SphereCollision object, which is inherited from Chumpy. Here is the code in bodyfit.py

sp = _SphereCollisions(pose=sv.pose,
                               betas=sv.betas,
                               model=model,
                               regs=_REGRESSORS)
Did we need a specific version of chumpy? 

Thanks,
Hai

**Comment by classner** [comment]
It *should* not require a specific chumpy version, but I think I used 0.66 if you want to try that one.

**Comment by haithanhp** [comment]
Hi,

When I updated chumpy into 0.66, I got this error for initializing camera.

<img width="873" alt="screen shot 2018-01-07 at 2 41 08 pm" src="https://user-images.githubusercontent.com/25809722/34653374-f1670bba-f3b8-11e7-9b25-e63549bd4fb1.png">
