### ISSUE TITLE
Can not download dataset and SMPL

### ISSUE THREAD

**Issue by haithanhp** [classner/generating_people#3]
Hi @classner ,

Thanks for you interesting work. I try to download the dataset and smpl, but the link is broken and nothing is responsed.
smpl:  http://smpl.is.tue.mpg.de/downloads
dataset: http://files.is.tuebingen.mpg.de/classner/gp/

I also try to run scripts in generation/tools, but where do you download the data and their segmentation? I can not generate data by scripts without segmentation folder.
 
Could you help to show me how to download these stuffs? 

Thanks,
Hai

**Comment by classner** [comment]
Hi!

Thank you for your interest in the dataset and SMPL! The servers of our institute are currently being moved, it should be available again very soon. I see that the SMPL website is up and running again, the dataset website should also be available again soon.

Sorry for the inconvenience,
Christoph

**Comment by haithanhp** [comment]
Hi,

Thank you for letting me know. I tried to run all scripts to generate your processed data. I got the Chictopia10K from this (https://github.com/lemondan/HumanParsing-Dataset). However, when I run script ./05_run_fit.sh, it gives me the error of miss match dimension for creating sphere collision object. By the way, when I run script 04 for deeper_cut, I do not see python file of deeper_cut.py so I tried to use file pose.py. Is it ok? 

Thanks,
Hai

**Comment by classner** [comment]
Hi!

The servers are up and running again, so you can download ChictopiaPlus directly. Once again, sorry for the inconvenience and thanks for reporting your issues (I'll respond to the other issue directly).

Yes, you can run `pose.py` just as well, it should produce even better poses with the dense keypoints. We were only using the deepercut CNN at the time to keep the two papers independent as we couldn't be sure about acceptance.

Best,
Christoph
