### ISSUE TITLE
out of index in get_objective function of SphereCollision object

### ISSUE THREAD

**Issue by haithanhp** [classner/generating_people#5]
Hi @classner,

Thank you for updating the code. I re-run ./05_run_fits.sh, but there is another error of out of index in the following code in SphereCollision.py:

def get_objective(self):
    print('get objective')
    return ch.sum((ch.exp(-((ch.sum((self.sph_v[self.ids0]-
                                     self.sph_v[self.ids1])**2,
                                    axis=1))/(self.radiuss))/2.))**2)**.5

**self.sph_v** only has 3 elements, while **self.ids0** and **self.ids1** has larger value. Could you help to see the image below?

<img width="802" alt="screen shot 2018-01-08 at 6 38 58 pm" src="https://user-images.githubusercontent.com/25809722/34697902-3cb2c588-f4a3-11e7-9f64-d844bd0b6770.png">

Best,
Hai

**Comment by classner** [comment]
Hi @HaiPhan1991,

I assume that this is a problem unrelated to the sphere dimensionality, but originates from the fact that you used the dense keypoint pose estimation (with 91 keypoints) from the `up` project as compared to the 14 standard keypoints that I used for the paper. For the 91 keypoints, the spheres for the inner penetration avoidance will probably be not well defined. If you just omit the `--use_inner_penetration` flag, it should run.

Just to make sure, you can send me an email with the inputs for the fitting on this file and I'll double check (also I should add a more meaningful error message for this case ;) ).

Best,
Christoph

**Comment by haithanhp** [comment]
Hi,

I want to reproduce your procedure on my custom data just like your chicopitaPlus. I downloaded source code and model on (https://github.com/eldar/deepcut-cnn) to extract pose by script ./04_deeper_cut.sh using pose.py, however it is not exactly your pose results. They are like this:
mine
<img width="200" alt="screen shot 2018-01-08 at 7 59 36 pm" src="https://user-images.githubusercontent.com/25809722/34700022-a70a5f58-f4ae-11e7-9c1a-57976e77c868.png">
 yours:
<img width="201" alt="screen shot 2018-01-08 at 8 01 35 pm" src="https://user-images.githubusercontent.com/25809722/34700039-c2fa4eda-f4ae-11e7-88a2-80fa7a5a64d5.png">

Could you show me the right models or steps to get your silhouette result?

Thanks,
Hai

**Comment by haithanhp** [comment]
Thanks for your support. I solved this issue. Just replace testpy_val_91_500_pkg.prototxt file to ResNet152.prototxt in pose.py. By the way, I double check that I have already used 14 keypoints but I still can not use inner_penetration option in ./05_run_fits.sh.

**Comment by classner** [comment]
Could you send me an email with your inputs so that I can track down the issue? For me the fitting works and I can not reproduce it...

**Comment by haithanhp** [comment]
Hi,

I sent you an email. Just double check. Let me know if you have not received yet.

Thanks,
Hai

**Comment by classner** [comment]
I'm sorry, I did not receive the email (I assume you wrote to the email [here](http://ps.is.tue.mpg.de/person/classner)). Could you please re-send it? Alternatively, you can reach me at [myusername]@amazon.com. Thanks a lot!

**Comment by haithanhp** [comment]
Hi,
I have re-sent an email. I also ask you some questions. If you still do not receive it, just let me know

Thanks,

**Comment by classner** [comment]
Hi @HaiPhan1991!

I did not hear back from you after responding to your mail, are your questions answered! :)

Best,
Christoph

**Comment by haithanhp** [comment]
Hi @classner,

Sorry for that. I am busy on these days. Yeah, I also try your new code and the result is very impressive. Thank you for your very kind support. If I have anything, I will talk to you. I will close this issue.

Best,
Hai

**Comment by classner** [comment]
Hi @HaiPhan1991,

I am glad to hear that! Thank you for your persistence and support in tracking down these issues. I'll be glad to help if other things are coming up.

Best,
Christoph
