### ISSUE TITLE
error while running run.py

### ISSUE THREAD

**Issue by perseus784** [classner/generating_people#7]
I am getting this error:
Exception: `/home/drive/generate_people/generating_people-master/generation/data/people/full` contains no files for this mode
Which are the files that should be put in this folder and how to get it?

**Comment by classner** [comment]
The run.py script is looking for a tfrecord database in that folder. To see how precisely the path is constructed, see here: https://github.com/classner/generating_people/blob/master/generation/data.py#L24 and of course change it to your needs.

Best,
Christoph
