### ISSUE TITLE
Can not download dataset and SMPL again

### ISSUE THREAD

**Issue by Meric3** [classner/generating_people#9]
Hi @classner ,

I check closed issue about smpl dataset link, but it looks like it happened again.

http://smpl.is.tue.mpg.de/signup

I can't sign up this smpl site so I can't download smpl dataset and library. 
When I click it sign up button, it says " We're sorry, but something went wrong. ".

Could you help to show me how to download these stuffs?

Thanks,
JH Moon.

**Comment by Limbbo** [comment]
same issue anyone with the solutions?

**Comment by classner** [comment]
Hi @Meric3 ,

I just tried to sign up myself again and everything worked as expected. Have you maybe used non-ASCII characters for your name or email address? I fear there could be a problem with that in the backend of the application.

Best,
Christoph

**Comment by Meric3** [comment]
Hello @classner ,

Recently, I request this issue in smpl site email. 
I was able to solve this problem with the kind answers of the mail.
Now it is not show "We~" message.

Thank you for your response.
